/**
 * مزامنة منظومة المصروفات مع قاعدة البيانات السحابية.
 * الاستراتيجية: التخزين المحلي يظل الكاش السريع، والمزامنة تتم في الخلفية.
 */

import { supabase } from "@/integrations/supabase/client";
import { withRetry } from "@/lib/retry";
import { enqueueOffline } from "@/lib/offline-queue";
import type { ExpenseMeta, RecurringExpense, CategoryBudget, CustomExpenseCategory } from "@/lib/expenses-system";

const table = (name: string) => (supabase.from as any)(name);

async function uid(): Promise<string | null> {
  try {
    const { data } = await supabase.auth.getUser();
    return data.user?.id ?? null;
  } catch {
    return null;
  }
}

/* ==================== Push Functions ==================== */

export async function pushExpenseMeta(expenseId: string, meta: ExpenseMeta): Promise<void> {
  const user_id = await uid();
  if (!user_id) return;
  const payload = {
    id: expenseId, user_id, expense_id: expenseId,
    account_id: meta.accountId || null, branch_id: meta.branchId || null,
    cost_center: meta.costCenter || null, voucher_number: meta.voucherNumber || null,
    receipt_url: meta.receiptUrl || null,
    custom_fields: { accountName: meta.accountName, branchName: meta.branchName, recipientName: meta.recipientName, receiptName: meta.receiptName, isRecurring: meta.isRecurring, recurringTemplateId: meta.recurringTemplateId, autoGenerated: meta.autoGenerated },
  };
  try { await withRetry(() => table("expense_metadata").upsert(payload)); } catch { enqueueOffline({ tableName: "expense_metadata", operation: "upsert", payload }); }
}

export async function pushRecurringExpense(item: RecurringExpense): Promise<void> {
  const user_id = await uid();
  if (!user_id) return;
  const payload = { id: item.id, user_id, category: item.category, amount: item.amount, description: item.title, frequency: item.frequency === "daily" || item.frequency === "weekly" ? "monthly" : item.frequency, next_due_date: item.nextDueDate, is_active: item.active };
  try { await withRetry(() => table("recurring_expenses").upsert(payload)); } catch { enqueueOffline({ tableName: "recurring_expenses", operation: "upsert", payload }); }
}

export async function removeRecurringExpense(id: string): Promise<void> {
  const user_id = await uid();
  if (!user_id) return;
  try { await withRetry(() => table("recurring_expenses").delete().eq("user_id", user_id).eq("id", id)); } catch { enqueueOffline({ tableName: "recurring_expenses", operation: "delete", payload: { id, user_id } }); }
}

export async function pushCategoryBudget(budget: CategoryBudget): Promise<void> {
  const user_id = await uid();
  if (!user_id) return;
  const payload = { user_id, category: budget.category, monthly_budget: budget.monthlyLimit, alert_threshold: budget.warnThresholdPct };
  try { await withRetry(() => table("category_budgets").upsert(payload, { onConflict: "user_id,category" })); } catch { enqueueOffline({ tableName: "category_budgets", operation: "upsert", payload }); }
}

export async function removeCategoryBudget(category: string): Promise<void> {
  const user_id = await uid();
  if (!user_id) return;
  try { await withRetry(() => table("category_budgets").delete().eq("user_id", user_id).eq("category", category)); } catch { enqueueOffline({ tableName: "category_budgets", operation: "delete", payload: { category, user_id } }); }
}

export async function pushCustomCategories(cats: CustomExpenseCategory[]): Promise<void> {
  const user_id = await uid();
  if (!user_id) return;
  const payload = { user_id, custom_categories: cats };
  try { await withRetry(() => table("expense_settings").upsert(payload, { onConflict: "user_id" })); } catch { enqueueOffline({ tableName: "expense_settings", operation: "upsert", payload }); }
}

/* ==================== Pull Function ==================== */

export async function pullExpensesFromCloud(): Promise<boolean> {
  const user_id = await uid();
  if (!user_id) return false;

  const [metaRes, recurringRes, budgetsRes, settingsRes] = await Promise.all([
    table("expense_metadata").select("*").eq("user_id", user_id),
    table("recurring_expenses").select("*").eq("user_id", user_id).eq("is_active", true),
    table("category_budgets").select("*").eq("user_id", user_id),
    table("expense_settings").select("*").eq("user_id", user_id).maybeSingle(),
  ]);

  const mod = await import("@/lib/expenses-system");

  // Restore custom categories from settings
  if (!settingsRes.error && settingsRes.data?.custom_categories) {
    mod.saveExpenseCategories(settingsRes.data.custom_categories);
  }

  // Restore expense metadata
  if (!metaRes.error && Array.isArray(metaRes.data)) {
    const metaMap: Record<string, ExpenseMeta> = {};
    metaRes.data.forEach((row: any) => {
      const cf = row.custom_fields || {};
      metaMap[row.expense_id] = {
        accountId: row.account_id || cf.accountId,
        accountName: cf.accountName,
        branchId: row.branch_id || cf.branchId,
        branchName: cf.branchName,
        costCenter: row.cost_center || cf.costCenter,
        recipientName: cf.recipientName,
        voucherNumber: row.voucher_number || cf.voucherNumber,
        receiptUrl: row.receipt_url || cf.receiptUrl,
        receiptName: cf.receiptName,
        isRecurring: cf.isRecurring,
        recurringTemplateId: cf.recurringTemplateId,
        autoGenerated: cf.autoGenerated,
      };
    });
    // Merge with local
    const STORAGE_KEY = "segilly_expense_meta_map_v1";
    const existing = JSON.parse(localStorage.getItem(STORAGE_KEY) || "{}");
    localStorage.setItem(STORAGE_KEY, JSON.stringify({ ...metaMap, ...existing }));
  }

  // Restore recurring expenses
  if (!recurringRes.error && Array.isArray(recurringRes.data) && recurringRes.data.length > 0) {
    const items: RecurringExpense[] = recurringRes.data.map((r: any) => ({
      id: r.id,
      title: r.description || "",
      amount: Number(r.amount || 0),
      category: r.category,
      accountId: "acc-cash-main",
      frequency: r.frequency || "monthly",
      dayOfMonth: new Date(r.next_due_date).getDate(),
      startDate: r.next_due_date,
      nextDueDate: r.next_due_date,
      autoApprove: false,
      active: r.is_active !== false,
      createdAt: r.created_at,
    }));
    mod.saveRecurringExpenses(items);
  }

  // Restore budgets
  if (!budgetsRes.error && Array.isArray(budgetsRes.data) && budgetsRes.data.length > 0) {
    const budgets: CategoryBudget[] = budgetsRes.data.map((r: any) => ({
      category: r.category,
      monthlyLimit: Number(r.monthly_budget || 0),
      warnThresholdPct: Number(r.alert_threshold || 80),
    }));
    mod.saveCategoryBudgets(budgets);
  }

  return true;
}
