import { useEffect, useMemo, useState } from "react";
import { BezelCard } from "@/components/BezelCard";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { getStoreOrderEvents, getOrderPayments, type StoreOrder, type StoreOrderEvent, type StorefrontPayment } from "@/lib/storefront";
import { ChevronLeft, ChevronRight, CreditCard, History, Search } from "lucide-react";
import { toast } from "sonner";

const labels: Record<string, string> = { submitted: "طلب جديد", under_review: "قيد المراجعة", needs_info: "محتاج بيانات", accepted: "تم القبول", invoiced: "اتحول لفاتورة", shipped: "اتشحن", delivered: "تم التسليم", rejected: "مرفوض", cancelled: "ملغي", expired: "انتهت المهلة" };
const paymentLabels: Record<string, { text: string; variant: "default" | "secondary" | "destructive" | "outline" }> = {
  unpaid: { text: "غير مدفوع", variant: "outline" },
  pending: { text: "بانتظار الدفع", variant: "secondary" },
  paid: { text: "مدفوع", variant: "default" },
  failed: { text: "فشل الدفع", variant: "destructive" },
  refunded: { text: "مرتجع", variant: "destructive" },
};
const filters = ["all", "submitted", "under_review", "needs_info", "accepted", "invoiced", "shipped", "delivered", "rejected", "cancelled", "expired"];

export function StorefrontOrders({ orders, onRefresh, onUpdate, onInvoice }: { orders: StoreOrder[]; onRefresh: () => Promise<void>; onUpdate: (order: StoreOrder, action: "accepted" | "rejected" | "under_review", reason?: string) => Promise<void>; onInvoice: (order: StoreOrder) => Promise<void> }) {
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState("all"); const [page, setPage] = useState(1); const [selected, setSelected] = useState<StoreOrder | null>(null); const [events, setEvents] = useState<StoreOrderEvent[]>([]); const [selectedPayments, setSelectedPayments] = useState<StorefrontPayment[]>([]);
  const filtered = useMemo(() => orders.filter((order) => (filter === "all" || order.status === filter) && `${order.public_number} ${order.customer_name} ${order.customer_phone}`.toLowerCase().includes(query.trim().toLowerCase())), [orders, filter, query]);
  const pages = Math.max(1, Math.ceil(filtered.length / 6)); const visible = filtered.slice((page - 1) * 6, page * 6); const open = orders.filter((order) => ["submitted", "under_review", "needs_info"].includes(order.status)).length; const revenue = orders.filter((order) => ["accepted", "invoiced", "shipped", "delivered"].includes(order.status)).reduce((sum, order) => sum + order.total, 0);
  useEffect(() => { setPage(1); }, [filter, query]); useEffect(() => { if (page > pages) setPage(pages); }, [page, pages]);
  const details = async (order: StoreOrder) => { setSelected(order); try { const [ev, pay] = await Promise.all([getStoreOrderEvents(order.id), getOrderPayments(order.id)]); setEvents(ev); setSelectedPayments(pay); } catch { toast.error("تعذر تحميل سجل الطلب"); } };
  const reject = async (order: StoreOrder) => { const reason = window.prompt("سبب رفض الطلب"); if (reason?.trim()) await onUpdate(order, "rejected", reason.trim()); };
  return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-3"><Summary label="طلبات اليوم" value={orders.filter((order) => new Date(order.created_at).toDateString() === new Date().toDateString()).length} /><Summary label="تحتاج إجراء" value={open} /><Summary label="قيمة المقبول" value={`${revenue.toLocaleString("en-US")} ج.م`} /></div><div className="sticky top-3 z-10 grid gap-3 rounded-2xl border border-border/70 bg-background/90 p-3 shadow-lg backdrop-blur md:flex"><div className="relative flex-1"><Search className="absolute right-3 top-3 h-4 w-4 text-muted-foreground" /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="ابحث برقم الطلب أو اسم العميل أو الهاتف" className="pr-10" /></div><div className="flex gap-1 overflow-x-auto">{filters.map((value) => <Button key={value} size="sm" variant={filter === value ? "default" : "ghost"} onClick={() => setFilter(value)}>{value === "all" ? "الكل" : labels[value]}</Button>)}</div></div>{visible.length === 0 ? <BezelCard className="p-10 text-center text-muted-foreground">مفيش طلبات مطابقة.</BezelCard> : <div className="grid gap-3">{visible.map((order) => <BezelCard key={order.id} className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><button type="button" className="text-right" onClick={() => void details(order)}><p className="font-bold">طلب #{order.public_number} · {order.customer_name}</p><p className="mt-1 text-sm text-muted-foreground">{order.customer_phone} · {order.total.toLocaleString("en-US")} ج.م · {labels[order.status]}</p></button><div className="flex flex-wrap items-center gap-2">{order.order_type === "online_payment" && <Badge variant={paymentLabels[order.payment_status]?.variant ?? "outline"} className="gap-1"><CreditCard className="h-3 w-3" /> {paymentLabels[order.payment_status]?.text ?? order.payment_status}</Badge>}</div></div>{["submitted", "under_review", "needs_info"].includes(order.status) && <div className="mt-3 flex flex-wrap gap-2"><Button size="sm" onClick={() => void onUpdate(order, "accepted")}>قبول وحجز</Button><Button size="sm" variant="outline" onClick={() => void reject(order)}>رفض</Button></div>}{order.status === "accepted" && <div className="mt-3"><Button size="sm" onClick={() => void onInvoice(order)} disabled={order.order_type !== "cash_on_delivery" && order.order_type !== "online_payment"}>{order.order_type === "online_payment" && order.payment_status === "paid" ? "تأكيد و إنشاء فاتورة" : "إنشاء فاتورة"}</Button></div>}</BezelCard>)}</div>}
    {selected && <div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4" onClick={() => { setSelected(null); setSelectedPayments([]); }}><BezelCard className="w-full max-w-lg max-h-[80vh] overflow-y-auto p-6" onClick={(e) => e.stopPropagation()}><div className="flex items-center justify-between"><h3 className="text-lg font-black">تفاصيل طلب #{selected.public_number}</h3><Button variant="ghost" size="sm" onClick={() => { setSelected(null); setSelectedPayments([]); }}>✕</Button></div><div className="mt-4 space-y-2 text-sm"><p><b>العميل:</b> {selected.customer_name} — {selected.customer_phone}</p><p><b>العنوان:</b> {selected.delivery_address}</p><p><b>الإجمالي:</b> {selected.total.toLocaleString("en-US")} ج.م</p><p><b>الحالة:</b> {labels[selected.status]}</p><p><b>الدفع:</b> {paymentLabels[selected.payment_status]?.text ?? selected.payment_status} {selected.order_type === "online_payment" && <Badge variant="outline" className="mr-1"><CreditCard className="h-3 w-3" /> أونلاين</Badge>}</p>{selectedPayments.length > 0 && <div className="mt-3 rounded-xl border p-3"><p className="font-bold text-xs text-muted-foreground mb-2">سجل الدفع</p>{selectedPayments.map((p) => <div key={p.id} className="flex items-center justify-between text-xs py-1"><span>{new Date(p.created_at).toLocaleDateString("ar-EG")}</span><Badge variant={paymentLabels[p.status]?.variant ?? "outline"}>{paymentLabels[p.status]?.text ?? p.status}</Badge><span>{(p.amount_cents / 100).toFixed(2)} {p.currency}</span></div>)}</div>}</div><div className="mt-5 border-t pt-4"><p className="text-xs font-bold text-muted-foreground mb-2"><History className="inline h-3 w-3" /> سجل الطلب</p><div className="space-y-2">{events.map((ev) => <div key={ev.id} className="rounded-xl bg-muted/50 p-2 text-xs"><p className="font-bold">{ev.event_type}</p><p className="text-muted-foreground">{new Date(ev.created_at).toLocaleString("ar-EG")}</p></div>)}</div></div></BezelCard></div>}
  </div>;
}
function Summary({ label, value }: { label: string; value: number | string }) { return <BezelCard variant="flat" className="p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-black">{value}</p></BezelCard>; }
