// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';
import { describeEnvSource, getBundledFallback, getRuntimeConfig } from '@/lib/app-config';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}


function createSupabaseClient() {
  // Resolution order: build-time VITE_* (normal case) -> runtime
  // /app-config.json (loaded in root beforeLoad; survives broken builds)
  // -> bundled fallback (same values, inlined at build; survives undelivered
  // static files) -> process.env (SSR). See src/lib/app-config.ts.
  const runtime = getRuntimeConfig();
  const bundled = getBundledFallback();
  const SUPABASE_URL =
    import.meta.env['VITE_SUPABASE_URL'] || runtime?.url || bundled?.url || process.env['SUPABASE_URL'];
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env['VITE_SUPABASE_PUBLISHABLE_KEY'] ||
    runtime?.key ||
    bundled?.key ||
    process.env['SUPABASE_PUBLISHABLE_KEY'];

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    let source = "unknown";
    try {
      source = describeEnvSource();
    } catch {
      // never block the actionable error on diagnostics
    }
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud. (config source: ${source}; want VITE_SUPABASE_URL + VITE_SUPABASE_PUBLISHABLE_KEY at build, or /app-config.json at runtime)`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  // One-line, value-free diagnostics: which source won (never prints secrets).
  try {
    console.info(`[Supabase] client configured via ${describeEnvSource()}`);
  } catch {
    // never block client creation on logging
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

